### ISSUE TITLE
Promo code for multiple usage

### ISSUE THREAD

**Issue by Chinese1904** [zgabievi/laravel-promocodes#12]
Hi @zgabievi 

I like your package and was thinking about using it myself, but I do have one question, because it seems to not be implemented yet:

- How would you approach the situation if you needed a promo code (like a coupon) that many users should be able to apply to their account? For instance, I send out a marketing campaign saying, "Act now and retrieve 20% off your total bill".

It seems it needs a little refactoring with the relationships.

Thanks!

**Comment by zgabievi** [comment]
Hi @Chinese1904 

Thank you for this suggestion. I've added this functionality in [1.0.1](https://github.com/zgabievi/laravel-promocodes/tree/1.0.1).
