### ISSUE TITLE
promocode migration

### ISSUE THREAD

**Issue by dayaki** [zgabievi/laravel-promocodes#13]
Am getting this error while trying to run `php artisan migrate` after installation:

`[Illuminate\Database\QueryException]                       
  SQLSTATE[42000]: Syntax error or access violation: 1064 Y  
  ou have an error in your SQL syntax; check the manual tha  
  t corresponds to your MySQL server version for the right   
  syntax to use near 'json null, `is_used` tinyint(1) not n  
  ull default '0') default character set utf8' at line 1 (S  
  QL: create table `promocodes` (`id` int unsigned not null  
   auto_increment primary key, `user_id` int unsigned null,  
   `code` varchar(32) not null, `reward` double(10, 2) null  
  , `data` json null, `is_used` tinyint(1) not null default  
   '0') default character set utf8mb4 collate utf8mb4_unico  
  de_ci) `

**Comment by zgabievi** [comment]
Your database wasn't able to pass json type. So I changed migration of `data` column, and it's now text type. You shouldn't have this problem anymore.
