### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by SubaruCode** [zgabievi/laravel-promocodes#17]
Please update to support Laravel 5.6

Thanks!

**Comment by zgabievi** [comment]
I'm on it. 👍

**Comment by hayreddintuzel** [comment]
we are waiting for 2 months :)

**Comment by drolean** [comment]
already done.. waiting for new release or use a 'dev-master'

**Comment by danpalmieri** [comment]
`Problem 1
    - Installation request for zgabievi/promocodes ^1.1 -> satisfiable by zgabievi/promocodes[1.1.0].
    - Conclusion: remove laravel/framework v5.6.22
    - Conclusion: don't install laravel/framework v5.6.22
    - zgabievi/promocodes 1.1.0 requires illuminate/config ~5.5.0 -> satisfiable by laravel/framework[5.5.x-dev], illuminate/config[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.22].
    - don't install illuminate/config 5.5.x-dev|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.0|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.16|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.17|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.2|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.28|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.33|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.34|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.35|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.36|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.37|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.39|don't install laravel/framework v5.6.22
    - don't install illuminate/config v5.5.40|don't install laravel/framework v5.6.22
    - Installation request for laravel/framework (locked at v5.6.22, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.22].`

**Comment by danpalmieri** [comment]
Thanks but is not installing in Laravel 5.6.** only in Laravel 5.6.0

**Comment by drolean** [comment]
try this `composer require zgabievi/promocodes:dev-master`

**Comment by zgabievi** [comment]
New version [1.2.0](https://github.com/zgabievi/laravel-promocodes/releases/tag/1.2.0) has been released. Thanks to @drolean . 🎉

**Comment by vonec** [comment]
can you update this to support laravel 5.8 ??
