### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by dayaki** [zgabievi/laravel-promocodes#2]
I keep getting this error when i add your package

`[Symfony\Component\Debug\Exception\FatalErrorException]
  parse error, expecting `']''`

**Comment by zgabievi** [comment]
Please update to new version 0.2.1 and it will be fixed

**Comment by Mohamed-Zedan** [comment]
I got this problem:

 - The requested package zgabievi/promocodes ^0.2.1 exists as zgabievi/promocodes[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, dev-master] but these are rejected by your constraint.
