### ISSUE TITLE
Promocode can be used more than once

### ISSUE THREAD

**Issue by yasir-lateef** [zgabievi/laravel-promocodes#25]
I believe this package is the best in the category. I noticed one anamoly, calling Promocodes::apply($code) doesn't insert into pivot table and so, a user can use a promocode more than once.

While reading the definition of apply method, i think this line isn't working as it must.

$promocode->users()->attach(auth()->user()->id,[
    'used_at' => Carbon::now(),
 ]);

I'm working to find a fix but I think you would have a better idea.

**Comment by yasir-lateef** [comment]
It is inserting promocode_id in place of user_id and null in place of promocode_id.

**Comment by zgabievi** [comment]
Thank you @yasir-lateef for your report. I would definitely work. Can you please give me some more info about issue, or better, give me a reproduction steps to follow and get this exception.

**Comment by yasir-lateef** [comment]
I think I tried to attach in the reverse order and got this exception i.e replacing

$promocode->users()->attach(auth()->user()->id,[
'used_at' => Carbon::now(),
]);

with

 auth()->user()->promocodes()->attach($promocode->id, [
                    'used_at' => Carbon::now(),
                ]);

**Comment by yasir-lateef** [comment]
The former doesn't generate any exceptions but returns an empty array of users relation, meaning no pivot entry.

**Comment by yasir-lateef** [comment]
@zgabievi Please review #26. I was  gettting 'null' for auth()->user()->id because for my model, it is 'user_id'. Now, when I replaced it with auth()->id(), I'm getting the same exception as before.

**Comment by yasir-lateef** [comment]
After a bit of though, I read the relationship method in `Promocode` Model and updated `foreign_pivot_key` to `promocode_id` in my `config/promocodes.php. `

Bam! I got it right!

![screenshot from 2018-08-11 19-43-08](https://user-images.githubusercontent.com/14800695/43992921-2ee80c24-9d9f-11e8-9367-becc2aa2f743.png)

**Comment by zgabievi** [comment]
And if you want to create code that will be one time use only, you can call Promocodes::createDisposable(); After first use it will be invalid for second use
