### ISSUE TITLE
Flexible subscription discounts

### ISSUE THREAD

**Issue by sandervanhooft** [zgabievi/laravel-promocodes#27]
Hi,

I think this package is great as it is for one-off payments.

I'm however working on a client (SDK) for a subscription payment service and looking for coupon discount solutions.

Are there any plans for supporting subscriptions (sequential transactions)? When looking at Stripe for example, they support these use cases:
>Coupons in Stripe provide discounts on recurring charges. Like subscriptions, coupons allow for great flexibility in how you define and use them. They can:
>- Apply to every invoice, just one invoice, or for a certain length of time
>- Reduce invoices by a percentage or a flat amount
>- Apply to every subscription a customer has or only specific ones

>You can even define a coupon that must be redeemed by a certain date or is limited to a set number of redemptions (across all of your customers).

It would be great to have a coupon package that supports cases like these.

**Comment by zgabievi** [comment]
Thank you for your request. I will note this to be next update.

**Comment by zgabievi** [comment]
Maybe it's already too late for the response, but better late than never. 
Every case you requested is supported by this package in latest release.

Fill free to ask questions, if you can't find in docs.
