### ISSUE TITLE
Redeem code on a user seems wrong

### ISSUE THREAD

**Issue by abhij89** [zgabievi/laravel-promocodes#29]
I just set up the library and gave it a try. Generated few promo codes, and tried redeeming one of the code, but it threw exception and made it clear that it is doing everything wrong.

Errors I noticed:

> The users and promocode_user tables relation is defined wrong. Query it is executing is for promocode id 12 and user id 41:
```select * from `users` inner join `promocode_user` on `users`.`id` = `promocode_user`.`user_id` where `promocode_user`.`user_id` = 12 and `promocode_user`.`user_id` = 41)```

>while it should have been:
```select * from `users` inner join `promocode_user` on `users`.`id` = `promocode_user`.`user_id` where `promocode_user`.`promocode_id` = 12 and `promocode_user`.`user_id` = 41)```

as a result of this, it was saving the wrong details in promocode_user table, instead of saving the user id in user_id column, it was trying to save promocode id in it.

created a pull-request #28 for the fix

**Comment by zgabievi** [comment]
Merged. Thanks
