### ISSUE TITLE
Feature request + Question

### ISSUE THREAD

**Issue by abhij89** [zgabievi/laravel-promocodes#30]
Question:
I am using `Promocode::check($code)` to check if promocode is available or not? But it is throwing `InvalidPromocodeException` exception, shouldn't it ideally return false, as that is the whole point of this function to check if code is valid or not?

Feature request:
- I don't see an option to let same user use same promo code multiple times say 2 or 3, how we do this?
- How do we generate user specific promocodes? Promo code applicable only for a particular user?

**Comment by zgabievi** [comment]
Does this issue still exists, after your pull request about second usage method? If not I will close it

**Comment by abhij89** [comment]
yes these are some new requests and issue.. these needs to be taken care of.

**Comment by zgabievi** [comment]
I know this is an old issue but, fixed check issue, quantity value is supported. Feel free to open separate issues for separate requests.
