### ISSUE TITLE
Custom Promocodes

### ISSUE THREAD

**Issue by idragon81** [zgabievi/laravel-promocodes#34]
Is it possible to have custom Promo codes like OFF20 or SALE50 or similar,
The use case is that these codes will be used on mobile applications mostly.

I couldn't find something like this in the documentation but analyzing the code it seems possible using the model directly (which I feel like is a hacky way to do it)

**Comment by zgabievi** [comment]
Sorry for late reply. I don't know If you need this now, but you can implement that functionality

```php
use Gabievi\Promocodes\Models\Promocode;

Promocode::create([ 'code' => 'ABCD123' ]);
```

Params you can pass are: 'code', 'reward', 'data', 'expires_at', 'is_disposable'
