### ISSUE TITLE
How to use this? theres little documentation on this

### ISSUE THREAD

**Issue by TareqAbughosh** [zgabievi/laravel-promocodes#35]
I've installed the package, I wanted to start using it but theres little to no documentation for that.. How can I use this in an admin page? I want to add/remove codes  but I don't know which model I should import and so on... 

Can someone explain please?

**Comment by zgabievi** [comment]
Hello @TareqAbughosh . I'm not sure if you are interested in this anymore, but I will answer your question anyways.

I think installation is not hard. If you want to implement package with your admin UI, you can use **Gabievi\Promocodes\Models\Promocode** model to access all promocodes, and display them or change them as you wish. They are related to users, so you can use this too.

If you have further questions, you can open new issue, I will be happy to help you.
