### ISSUE TITLE
Limit promotional codes by quantity, not by date.

### ISSUE THREAD

**Issue by OleksiiBrylin** [zgabievi/laravel-promocodes#36]
I want to have one promocode to use it 30 times with different users. 
Can I do it?

**Comment by ladaposamuel** [comment]
One promo code , can be used 30 times by anyone, is that right?

**Comment by maverickdude** [comment]
@ladaposamuel 
Yes, I think this is what @OleksiiBrylin wants.
This will be definitely a cool feature to have.

**Comment by zgabievi** [comment]
Check out 82f4fc1 we have merged #38 pull request from @OleksiiBrylin
