### ISSUE TITLE
Class 'Gabievi\Promocodes\PromocodesServiceProvider' not found the run command php artisan vendor:publish on laravel 5.7

### ISSUE THREAD

**Issue by rohanisuhadi** [zgabievi/laravel-promocodes#39]
i change 

'providers' => [
    // ...
    Gabievi\Promocodes\PromocodesServiceProvider::class
],

to

Gabievi\Promocodes\ServiceProvider::class,

**Comment by vonec** [comment]
this is fixed please update and try again
