### ISSUE TITLE
Feature request: Entering own promo codes and promos codes like lyft

### ISSUE THREAD

**Issue by heyaj19** [zgabievi/laravel-promocodes#40]
Can we enter our own promo codes and as well as pre-generated ones. 

Secondly was wondering if you can create the promo codes like LYFT. They give a 50$ coupon, where 5$ is applied per ride till 50 is done so 10 rides. 

Or any way you think I can use your packaged to do that ?

And can you please change "Amount" to "number" - I got super confused as to what the diff between amount and reward was

**Comment by heyaj19** [comment]
Another thing what if a user is using JWTauth, the auth trait wont work when you check if the promo code has already been applied to user?

**Comment by vonec** [comment]
> Can we enter our own promo codes and as well as pre-generated ones.

 use Promocode  model to create custom models

>Secondly was wondering if you can create the promo codes like LYFT. They give a 50$ coupon, where 5$ is applied per ride till 50 is done so 10 rides.Or any way you think I can use your packaged to do that ?

this package doesnt allow  coupon to be used multiple times . you should manage the logic separeately for it 

>And can you please change "Amount" to "number" - I got super confused as to what the diff between amount and reward was

haha you will get used to it

> Another thing what if a user is using JWTauth, the auth trait wont work when you check if the promo code has already been applied to user?

yeah i noticed that ... and ended up using Promocodes::apply ensuring there is authenticated user

**Comment by zgabievi** [comment]
We have added functionality to allow you to use codes multiple times. So I think this issue can be closed. But we can continue conversation
