### ISSUE TITLE
What is the date format for

### ISSUE THREAD

**Issue by keatwei** [zgabievi/laravel-promocodes#41]
What is the date format for additional data $expires_in?

my format is like this "2019-01-07 22:45:00", however using the
Promocodes::createDisposable($amount = 1, $reward = null, array $data = [], $expires_in = null);
the date store in different value

**Comment by vonec** [comment]
$expires_in is 
    protected $dates = ['expires_at'];
so a carbon instance shd be the way to go

**Comment by zgabievi** [comment]
expires_in is the amount of days while code is available. You can leave it empty and it will be available always
