### ISSUE TITLE
Non-global prefix on coupon creation.

### ISSUE THREAD

**Issue by sweatyc** [zgabievi/laravel-promocodes#48]
**Is your feature request related to a problem? Please describe.**
I wanted to make a coupon code for an event, and wanted to code having a prefix of the event, e.g. PAXG-XXXX. This is different from the global prefix config because this is used once here only.

**Describe the solution you'd like**
Add an optional parameter `prefix` on creating `Promocodes::create()`.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by zgabievi** [comment]
Thank you for your request. Great addition for the library. Now you can customise prefix/suffix without using global values.

Example:

```
Promocodes::setPrefix('ABC')->setSuffix('XYZ')->create(5);
```
