### ISSUE TITLE
Add cascade on delete in database migration.

### ISSUE THREAD

**Issue by sweatyc** [zgabievi/laravel-promocodes#49]
**Describe the bug**
In `promocode_user` table, it has 2 foreign keys to `user_id` and `promocode_id`, they should be cascade on delete. Or otherwise, the database throws an exception when trying to delete a `user` or `promocode` when a `promocode_user` entry exists.

**Expected behavior**
Add `->onDelete('cascade')` in `2016_05_17_221000_create_promocodes_table.php`
```
$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
$table->foreign('promocode_id')->references('id')->on(config('promocodes.table', 'promocodes'))->onDelete('cascade');
```

**Comment by usamaejaz** [comment]
Also having this issue. It should `cascade` on delete.

**Comment by zgabievi** [comment]
You can now use `vendor:publish` to publish migrations and refactor them locally.
