### ISSUE TITLE
Wrong Disposable promo codes

### ISSUE THREAD

**Issue by evd1ser** [zgabievi/laravel-promocodes#51]
https://github.com/zgabievi/laravel-promocodes/blob/f7e9ed907ad504d74d8b9ed4d963ffa13842153e/src/Traits/Rewardable.php#L37
When I want to apply promo code to user twice throw AlreadyUsedException but promo code can use much time... 

May be need add conditional: if ($promocode->isDisposable() && $promocode->users()->wherePivot(config('promocodes.related_pivot_key'), $this->id)->exists()) {

**Comment by zgabievi** [comment]
Will be resolved in next release.
