### ISSUE TITLE
Couldn't install with 5.7 and migrations mismatch

### ISSUE THREAD

**Issue by Lotuashvili** [zgabievi/laravel-promocodes#52]
This package can't be installed on 5.7 version of Laravel.

![image](https://user-images.githubusercontent.com/6238393/71784324-d84e3900-300b-11ea-9cca-9ac9b6f27d68.png)

**IMPORTANT:** If the minimum version is 5.8, then user_id must be **bigInteger** instead of **integer** in migrations.

**Comment by indovsky** [comment]
I have this same problem

**Comment by zgabievi** [comment]
Added support for Laravel 5.7 and pushed to older releases [2.1.2](https://github.com/zgabievi/laravel-promocodes/tree/2.1.2). 

Tests are passing. Feel free to create new issue if it won't work for you
