### ISSUE TITLE
promocode_user not getting inserted

### ISSUE THREAD

**Issue by fadlisaad** [zgabievi/laravel-promocodes#56]
**Describe the bug**
I'm having issue with the `promocode_user` table which is not inserted once successfully redeem using **Redeemable** `applyCode`. Empty data on `users`

**To Reproduce**
1. Default setting on fresh laravel 5.8 install

**Expected behavior**
After redeem, expect the user_id and promocode_id is added into`promocode_user` and `users` response is not empty

**Screenshots**
`{
    "success": true,
    "data": {
        "id": 1,
        "code": "T3YT-HS8C",
        "reward": 30,
        "quantity": 86,
        "data": {
            "restaurant_id": "1"
        },
        "is_disposable": false,
        "expires_at": "2020-05-28 00:00:00",
        "created_at": null,
        "updated_at": "2020-05-27 16:18:26",
        "users": []
    },
    "message": "Successfully redeem the promo code"
}`

**Versions (please complete the following information):**
 - Laravel: [5.8]
 - PHP [7.4]

**Additional context**
-none-

**Comment by zgabievi** [comment]
Sorry but I couldn't understand your issue correctly. Can you provide some more details?

**Comment by fadlisaad** [comment]
Okay it has been solved. Sorry. Issue with my auth Middleware
