### ISSUE TITLE
Request update to support Laravel 8

### ISSUE THREAD

**Issue by stevewaughbitrix** [zgabievi/laravel-promocodes#57]

**Comment by ngunyimacharia** [comment]
I've created a pull request here: https://github.com/zgabievi/laravel-promocodes/pull/58

**Comment by ngunyimacharia** [comment]
Thank you for merging the pull request @zgabievi. I think we can close this issue now. - @stevewaughbitrix

**Comment by stevewaughbitrix** [comment]
Thank you soo much
