### ISSUE TITLE
You have changed an important behavior: Throw AlreadyUsedException when user used it twice but other user can still use it

### ISSUE THREAD

**Issue by pmochine** [zgabievi/laravel-promocodes#62]
Unfortunately with [this change](https://github.com/zgabievi/laravel-promocodes/commit/25a8010fd05ac676a3c2c63023c7c0c2c9dde816) you have removed an important behaviour:

    /** @test */
    public function it_throws_exception_coupon_was_used_before()
    {
        $this->signIn();

        Coupon::redeem($this->coupon['code']);

        $this->expectException('\Exception');
        $this->expectExceptionMessage(__('vue/checkout.coupon already used'));

        Coupon::redeem($this->coupon['code']);
    }

This test is now with the update failing for me. It used to catch the error `AlreadyUsedException`, but even when `is_disposable` was set to false.

This is important for this use-case: "Every user gets to use a Promocode, but every user only once'. 

The first test and this second test need to be true so that Promocode is working again.

    /** @test */
    public function multiple_users_can_use_the_same_promocode()
    {
        $this->signIn();

        $this->assertInstanceOf('Gabievi\Promocodes\Models\Promocode', Coupon::redeem($this->coupon['code']));

        $this->signIn(); // second user
        
        $this->assertInstanceOf('Gabievi\Promocodes\Models\Promocode', Coupon::redeem($this->coupon['code']));
    }

I know that the alternative would be to use `isSecondUsageAttempt`.

If you don't want to change the code, please update the readme file since it still says `Also if authenticated user will try to apply code twice, it will throw an exception`

**Comment by zgabievi** [comment]
I’m working on a new version of this package. Where every test case will be covered and code base will be updated.

**Comment by pmochine** [comment]
@zgabievi Don't worry I know this feeling if you don't have time for everything :D

Just want to add a thing: `isSecondUsageAttempt` is also not working when it's not `is_disposable`

**Comment by iamine** [comment]
i just come to report the same issue :)

**Comment by zgabievi** [comment]
Code is completely rewritten. Closing this issue by now. If you encounter the same problem, feel free to open the issue again.
