### ISSUE TITLE
Add doctrine/dbal 3.0.0

### ISSUE THREAD

**Issue by peterjaap** [zgabievi/laravel-promocodes#63]
**Is your feature request related to a problem? Please describe.**
I can't upgrade to doctrine/dbal 3.0.0 because of the dependency on ^2.10 from this package.

**Describe the solution you'd like**
Add ^3 as a version constraint.

**Comment by peterjaap** [comment]
Here's a PR, I've also added PHP8, seems to work fine!

https://github.com/zgabievi/laravel-promocodes/pull/64

**Comment by WildEgo** [comment]
+1 Would be amazing to merge it, everything seems to be working and current version is breaking something I'm working on.
