### ISSUE TITLE
Add properties

### ISSUE THREAD

**Issue by Krato** [zgabievi/laravel-promocodes#7]
Hi, your package is really good.

But what about to be able to add some properties to the promo. So we can retrieve later.

Like this package uses: [https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/adding-custom-properties](https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/adding-custom-properties).

What do you think?

**Comment by zgabievi** [comment]
Good idea. I will work on that. Thanks

**Comment by zgabievi** [comment]
Check new additional data feature here [how-to-use-additional-data](https://github.com/zgabievi/laravel-promocodes#how-to-use-additional-data). 
It's released since version [0.4.1](https://github.com/zgabievi/laravel-promocodes/tree/0.4.1)
