### ISSUE TITLE
apply promocode facade does not use the column name specified in config file

### ISSUE THREAD

**Issue by sahilsethchd** [zgabievi/laravel-promocodes#71]
**Describe the bug**
If i change the  'foreign_pivot_key' => 'promocode_id' (default) to  'foreign_pivot_key' => 'promo_code_id', then apply promoccode gives the error "promocode_id column not found in pivot table"

**To Reproduce**
1. Install this package
2. Goto promocodes.php config file and set 'foreign_pivot_key' => 'promo_code_id'
3. Generate any promocode and try to apply with the authenticated user.
4. See error ("promocode_id column not found in pivot table")

please refer to the funccitonal below:

/**
     * Apply promocode to user that it's used from now.
     *
     * @param string $code
     *
     * @return bool|Promocode
     * @throws AlreadyUsedException
     * @throws UnauthenticatedException
     */
    public function apply($code)
    {
        if (!auth()->check()) {
            throw new UnauthenticatedException;
        }

        if ($promocode = $this->check($code)) {
            if ($this->isSecondUsageAttempt($promocode)) {
                throw new AlreadyUsedException;
            }

            $promocode->users()->attach(auth()->id(), [
                'promocode_id' => $promocode->id,
                'used_at' => Carbon::now(),
            ]);

            if (!is_null($promocode->quantity)) {
                $promocode->quantity -= 1;
                $promocode->save();
            }

            return $promocode->load('users');
        }

        return false;
    }

In the above function, promocode_id is hardcoded which should be readable from config file.

**Comment by zgabievi** [comment]
This is implemented in new release.
