### ISSUE TITLE
Would it be nice if we let user specify the Promocode model in the config file?

### ISSUE THREAD

**Issue by mahmudz** [zgabievi/laravel-promocodes#73]
**Is your feature request related to a problem? Please describe.**
I wanted to modify the Promocode model but the package uses the vendor model directly. Which reduces the scope for extension. Like, I modified the migration and included timestamps, but it was turned off at model level.

**Describe the solution you'd like**
I would like you have the Promocode model specified in the config file same as User model was specified.

**Comment by key60529** [comment]
> **Is your feature request related to a problem? Please describe.**
> I wanted to modify the Promocode model but the package uses the vendor model directly. Which reduces the scope for extension. Like, I modified the migration and included timestamps, but it was turned off at model level.
> 
> **Describe the solution you'd like**
> I would like you have the Promocode model specified in the config file same as User model was specified.

@mahmudz , not sure if you still need this feature, but there's a workaround which could solve the thing you require.
First, create your own Model as follow
```
<?php

namespace App\Models;

use Gabievi\Promocodes\Models\Promocode as ModelsPromocode;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Promocode extends ModelsPromocode
{
    use HasFactory;

    // save the timestamps when creating a new promocode
    protected static function boot() {
        parent::boot();

        static::creating(function ($promocode) {
            $promocode->created_at = now();
            $promocode->updated_at = now();
        });
    }
}

```

and then in your controller, you could use you own model instead of the vendor's one to create a custom promocode, then the promocode record you create would save with the timestamps.

Hope this could help.

**Comment by zgabievi** [comment]
It's now possible in new release
