### ISSUE TITLE
config values are not used in migration

### ISSUE THREAD

**Issue by neolikotsi** [zgabievi/laravel-promocodes#74]
https://github.com/zgabievi/laravel-promocodes/blob/cb708ae8c73ee469719c288baf6d12767c89d6d6/migrations/2016_05_17_221000_create_promocodes_table.php#L15

**Comment by neolikotsi** [comment]
Another place where reference to config value is not used

https://github.com/zgabievi/laravel-promocodes/blob/cb708ae8c73ee469719c288baf6d12767c89d6d6/src/Promocodes.php#L439

**Comment by neolikotsi** [comment]
Going to submit a pull request for the changes. There will be no breaking changes.

**Comment by zgabievi** [comment]
They are used now in new release
