### ISSUE TITLE
Any plans to improve the code quality of the package?

### ISSUE THREAD

**Issue by michael-rubel** [zgabievi/laravel-promocodes#77]
Hello, @zgabievi!

The package looks nice, but a bit outdated.
I faced some problems using it in production, had to override the main class.

What you'll say if I'll send the PR of a more modern typed version of the package, and probably with the option to point out the model to use? It will require PHP 8 and probably Laravel 8.x.

UPD: If someone's still interested in this thread, I've created the package with a similar purpose, with polymorphism, configurability, and code quality:
https://github.com/michael-rubel/laravel-couponables

**Comment by zgabievi** [comment]
Sure @michael-rubel. Feel free to open pr. I’m planning to rewrite this package to more structured code, just couldn’t find free time to work on that for now.

**Comment by michael-rubel** [comment]
A bit too late, but thanks for the answer!
Had to handle the case myself and created: https://github.com/michael-rubel/laravel-couponables

**Comment by michael-rubel** [comment]
@zgabievi A bit too late, but thanks for the answer!
Had to handle the case myself and created: https://github.com/michael-rubel/laravel-couponables
