### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by Johnnydoncom** [zgabievi/laravel-promocodes#86]
I can't get the package installed for laravel 9. Below is the error:
[InvalidArgumentException]
  Could not find a matching version of package zgabievi/laravel-promocodes. Check the package spelling, your version
  constraint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by zgabievi** [comment]
Old name for packagist was `zgabievi/promocodes`, now it's changed to `zgabievi/laravel-promocodes`. You can try installing again and create a new issue if it still won't work for you.
