### ISSUE TITLE
Typehint causing issues with custom user model

### ISSUE THREAD

**Issue by tlopez54** [zgabievi/laravel-promocodes#88]
**Describe the bug**
On methods such as `user()` on `Promocodes.php`, it is typehinted with `Illuminate\Foundation\Auth\User`, but if you are using a custom User model which doesn't use the default Authenticatable (e.g eloquent uuid pkg), then you can't really use any of this functionality or anything that takes User as a parameter since it's been typehinted this way.

**To Reproduce**
1. Don't use default `Authenticatable`
2. Try pass user as a param to any function in this pkg.

**Expected behavior**
Any custom user model should be allowed. Perhaps use the one provided in config file for this as well.

**Comment by zgabievi** [comment]
Fixed in #93
