### ISSUE TITLE
Validation promo code

### ISSUE THREAD

**Issue by hasanmonfared** [zgabievi/laravel-promocodes#89]
Hello, thank you for the package. What should be done when the user wants to apply the promo code? And the display of errors is intended?
I think validation should be added with Laravel
https://laravel.com/docs/9.x/validation#custom-validation-rules

**Comment by SachinBahukhandi** [comment]
@zgabievi Are you accepting PR as a feature request on this?

**Comment by zgabievi** [comment]
> @zgabievi Are you accepting PR as a feature request on this?

Sure <3

**Comment by zgabievi** [comment]
Added in #95
